### ISSUE TITLE
scritp/setup is not creating db

### ISSUE THREAD

**Issue by kirantpatil** [msjit/testcasedb#105]
Environment: 
[suser@dhcppc33 testcasedb]$ ruby -v
ruby 2.2.4p230 (2015-12-16 revision 53155) [x86_64-linux]

[suser@dhcppc33 testcasedb]$ ./script/setup -p
Updated secret key
Migrating production database
/home/suser/testcasedb/vendor/bundle/ruby/gems/activesupport-3.2.21/lib/active_support/values/time_zone.rb:270: warning: circular argument reference - now
/home/suser/testcasedb/vendor/bundle/ruby/gems/ruby-ole-1.2.11.7/lib/ole/types/base.rb:265: warning: duplicated key at line 266 ignored: 4095
rake aborted!
LoadError: cannot load such file -- test/unit/assertions
/home/suser/testcasedb/vendor/bundle/ruby/gems/activesupport-3.2.21/lib/active_support/dependencies.rb:251:in `require'
/home/suser/testcasedb/vendor/bundle/ruby/gems/activesupport-3.2.21/lib/active_support/dependencies.rb:251:in`block in require'
/home/suser/testcasedb/vendor/bundle/ruby/gems/activesupport-3.2.21/lib/active_support/dependencies.rb:236:in `load_dependency'
/home/suser/testcasedb/vendor/bundle/ruby/gems/activesupport-3.2.21/lib/active_support/dependencies.rb:251:in`require'
/home/suser/testcasedb/vendor/bundle/ruby/gems/blitz-0.1.30/lib/blitz/utils.rb:1:in `<top (required)>'
/home/suser/testcasedb/vendor/bundle/ruby/gems/activesupport-3.2.21/lib/active_support/dependencies.rb:251:in`require'
/home/suser/testcasedb/vendor/bundle/ruby/gems/activesupport-3.2.21/lib/active_support/dependencies.rb:251:in `block in require'
/home/suser/testcasedb/vendor/bundle/ruby/gems/activesupport-3.2.21/lib/active_support/dependencies.rb:236:in`load_dependency'
/home/suser/testcasedb/vendor/bundle/ruby/gems/activesupport-3.2.21/lib/active_support/dependencies.rb:251:in `require'
/home/suser/testcasedb/vendor/bundle/ruby/gems/blitz-0.1.30/lib/blitz/curl.rb:1:in`<top (required)>'
/home/suser/testcasedb/vendor/bundle/ruby/gems/activesupport-3.2.21/lib/active_support/dependencies.rb:251:in `require'
/home/suser/testcasedb/vendor/bundle/ruby/gems/activesupport-3.2.21/lib/active_support/dependencies.rb:251:in`block in require'
/home/suser/testcasedb/vendor/bundle/ruby/gems/activesupport-3.2.21/lib/active_support/dependencies.rb:236:in `load_dependency'
/home/suser/testcasedb/vendor/bundle/ruby/gems/activesupport-3.2.21/lib/active_support/dependencies.rb:251:in`require'
/home/suser/testcasedb/vendor/bundle/ruby/gems/blitz-0.1.30/lib/blitz.rb:36:in `<top (required)>'
/home/suser/.gem/ruby/gems/bundler-1.11.2/lib/bundler/runtime.rb:77:in`require'
/home/suser/.gem/ruby/gems/bundler-1.11.2/lib/bundler/runtime.rb:77:in `block (2 levels) in require'
/home/suser/.gem/ruby/gems/bundler-1.11.2/lib/bundler/runtime.rb:72:in`each'
/home/suser/.gem/ruby/gems/bundler-1.11.2/lib/bundler/runtime.rb:72:in `block in require'
/home/suser/.gem/ruby/gems/bundler-1.11.2/lib/bundler/runtime.rb:61:in`each'
/home/suser/.gem/ruby/gems/bundler-1.11.2/lib/bundler/runtime.rb:61:in `require'
/home/suser/.gem/ruby/gems/bundler-1.11.2/lib/bundler.rb:99:in`require'

**Comment by kirantpatil** [comment]
with ruby 2.1.0 the db migration issue resolved.
